spring:
  datasource:
    url: jdbc:mysql://192.168.0.8:3316/mcms-dev-5.2-4?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true
    username: mcms
    password: mcms
    filters: wall,mergeStat
    type: com.alibaba.druid.pool.DruidDataSource

